openapi: 3.1.0
info:
  title: FinEdge Ledger API
  description: "Backend demo in-memory per gestione clienti, conti e movimenti"
  version: 0.1.0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/customers/{id}:
    get:
      tags:
      - customer-controller
      operationId: get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDTO"
    put:
      tags:
      - customer-controller
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCustomerDTO"
        required: true
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDTO"
  /api/transactions/{accId}/debit:
    post:
      tags:
      - Transactions
      operationId: debit
      parameters:
      - name: accId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: amount
        in: query
        required: true
        schema:
          type: number
      - name: description
        in: query
        required: false
        schema:
          type: string
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TransactionDTO"
  /api/transactions/{accId}/credit:
    post:
      tags:
      - Transactions
      operationId: credit
      parameters:
      - name: accId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: amount
        in: query
        required: true
        schema:
          type: number
      - name: description
        in: query
        required: false
        schema:
          type: string
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TransactionDTO"
  /api/customers:
    get:
      tags:
      - customer-controller
      operationId: list
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerDTO"
    post:
      tags:
      - customer-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCustomerDTO"
        required: true
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDTO"
  /api/accounts:
    post:
      tags:
      - Accounts
      operationId: open
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAccountDTO"
        required: true
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AccountDTO"
  /api/transactions/{accId}:
    get:
      tags:
      - Transactions
      operationId: list_1
      parameters:
      - name: accId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TransactionDTO"
  /api/customers/by-fiscalCode:
    get:
      tags:
      - customer-controller
      operationId: byCfQuery
      parameters:
      - name: cf
        in: query
        required: true
        schema:
          type: string
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDTO"
  /api/customers/by-fiscalCode/{cf}:
    get:
      tags:
      - customer-controller
      operationId: byCfPath
      parameters:
      - name: cf
        in: path
        required: true
        schema:
          type: string
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDTO"
  /api/accounts/{id}:
    get:
      tags:
      - Accounts
      operationId: get_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AccountDTO"
  /api/accounts/by-customer/{customerId}:
    get:
      tags:
      - Accounts
      operationId: listByCustomer
      parameters:
      - name: customerId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccountDTO"
components:
  schemas:
    UpdateCustomerDTO:
      type: object
      properties:
        fullName:
          type: string
          minLength: 1
        email:
          type: string
        fiscalCode:
          type: string
          pattern: "^[A-Z]{6}[0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]$"
      required:
      - fullName
    CustomerDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        fullName:
          type: string
        email:
          type: string
        fiscalCode:
          type: string
    TransactionDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountId:
          type: string
          format: uuid
        amount:
          type: number
        type:
          type: string
        description:
          type: string
        createdAt:
          type: string
    CreateCustomerDTO:
      type: object
      properties:
        fullName:
          type: string
          minLength: 1
        email:
          type: string
        fiscalCode:
          type: string
          pattern: "^[A-Z]{6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{3}[A-Z]$"
      required:
      - fullName
    CreateAccountDTO:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
      required:
      - customerId
    AccountDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        iban:
          type: string
        balance:
          type: number
        customerId:
          type: string
          format: uuid
